version: '3'

services:

    angular:
        build: ./api
        ports:
            - 4202:4200
        command: >
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4202"
        networks:
            - red

    php:
        build: ./back/php
        ports:
        - 82:80
        volumes:
        - ./back/php/.htaccess:/var/www/html/.htaccess
        depends_on:
        - mysql
        networks:
            - red


    mysql:
        build: ./back/mysql
        ports:
            - 3302:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'MENU'
            MYSQL_USER: 'usuario'
            MYSQL_PASSWORD: 'usuario'
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - red

volumes:
    db-volume:

networks:
    red: