
services:

    angular:
        build: ./api
        volumes:
            - ./api/src/app:/usr/src/app
        ports:
            - 4202:4200
        networks:
            - red

    php:
        build: ./back/php
        depends_on:
            - mysql
            - angular
        ports:
            - 82:80
        volumes:
            - ./back/php/.htaccess:/var/www/html/php/.htaccess
            - ./php:/var/www/html/php
        networks:
            - red

    mysql:
        build: ./back/mysql
        ports:
            - 3302:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'MENU'
            MYSQL_USER: 'usuario'
            MYSQL_PASSWORD: 'usuario'
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - red

volumes:
    db-volume:


networks:
    red:
