version: '3'

services:

    angular:
        build: ./api
        networks:
            - red

    php:
        build: ./back/php
        depends_on:
            - mysql
        ports:
            - 82:80
        volumes:
            - ./back/php/.htaccess:/var/www/html/.htaccess
        networks:
            - red

    mysql:
        build: ./back/mysql
        ports:
            - 3302:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'MENU'
            MYSQL_USER: 'usuario'
            MYSQL_PASSWORD: 'usuario'
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - red

volumes:
    db-volume:


networks:
    red:
